name: Golangci lint
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
        env:
          GOFLAGS: -mod=mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --enable lll
          version: v1.54
          skip-pkg-cache: true
